"""baseline current schema

Revision ID: 20260915_0000
Revises:
Create Date: 2026-09-15 11:45:18.491051
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = "20260915_0000"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "input_option_suggestions",
        sa.Column("option_type", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("option_type", "value"),
    )
    op.create_table(
        "input_payment_reference_counters",
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("reference_date", "entry_type"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("project_type", sa.String(), nullable=False),
        sa.Column("overhead_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("profit_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("vat_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "contingency_budget", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "status", sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("system_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_key"),
    )
    op.create_table(
        "boq_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("boq_type", sa.String(), nullable=False),
        sa.Column("sheet_name", sa.String(), nullable=True),
        sa.Column("wbs_level", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("item_no", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column(
            "material_unit_price", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("labor_unit_price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total_material", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total_labor", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("grand_total", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("embedding", Vector(dim=768), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["boq_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("project_name", sa.String(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("reply", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("intent", sa.String(), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("next_actions", sa.JSON(), nullable=True),
        sa.Column("time_scope", sa.JSON(), nullable=True),
        sa.Column("context_item_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fund_buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("bucket_type", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance_start_date", sa.Date(), nullable=True),
        sa.Column(
            "protected_reserve", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bucket_type IN ('PROJECT', 'OPERATIONS')", name="ck_fund_bucket_type"
        ),
        sa.CheckConstraint("currency = 'THB'", name="ck_fund_bucket_currency"),
        sa.CheckConstraint(
            "status IN ('SETUP', 'ACTIVE', 'LOCKED')", name="ck_fund_bucket_status"
        ),
        sa.CheckConstraint(
            "balance_start_date IS NULL OR EXTRACT(DAY FROM balance_start_date) = 1",
            name="ck_fund_bucket_start_month",
        ),
        sa.CheckConstraint("protected_reserve >= 0", name="ck_fund_bucket_reserve"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fund_buckets_project_id"), "fund_buckets", ["project_id"], unique=True
    )
    op.create_table(
        "input_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("subcontractor_id", sa.String(), nullable=True),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("requester_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("request_date", sa.Date(), nullable=False),
        sa.Column("work_type", sa.String(), nullable=True),
        sa.Column("request_type", sa.String(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("vendor_name", sa.String(), nullable=True),
        sa.Column("vendor_tax_id", sa.String(), nullable=True),
        sa.Column("vendor_branch", sa.String(), nullable=True),
        sa.Column("vendor_address", sa.Text(), nullable=True),
        sa.Column("receipt_no", sa.String(), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("accounting_vat_mode", sa.String(), nullable=True),
        sa.Column(
            "accounting_wht_rate", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("account_no", sa.String(), nullable=True),
        sa.Column("account_name", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("approved_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("receipt_file_name", sa.String(), nullable=True),
        sa.Column("receipt_content_type", sa.String(), nullable=True),
        sa.Column("receipt_storage_key", sa.String(), nullable=True),
        sa.Column("external_ai_blocked", sa.Boolean(), nullable=False),
        sa.Column("ocr_raw_json", sa.JSON(), nullable=True),
        sa.Column("ocr_low_confidence_fields", sa.JSON(), nullable=True),
        sa.Column("is_duplicate_flag", sa.Boolean(), nullable=False),
        sa.Column("duplicate_reason", sa.Text(), nullable=True),
        sa.Column("duplicate_of_request_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_reference", sa.String(), nullable=True),
        sa.Column("accounting_ready", sa.Boolean(), nullable=False),
        sa.Column("accounting_readiness_errors", sa.JSON(), nullable=False),
        sa.Column("flowaccount_sync_status", sa.String(), nullable=False),
        sa.Column("flowaccount_expense_id", sa.String(), nullable=True),
        sa.Column("flowaccount_document_no", sa.String(), nullable=True),
        sa.Column("flowaccount_external_document_id", sa.String(), nullable=True),
        sa.Column("flowaccount_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flowaccount_sync_error", sa.Text(), nullable=True),
        sa.Column("flowaccount_attachment_status", sa.String(), nullable=False),
        sa.Column("flowaccount_attachment_error", sa.Text(), nullable=True),
        sa.Column(
            "flowaccount_attachment_synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("flowaccount_supplier_invoice_status", sa.String(), nullable=False),
        sa.Column("flowaccount_supplier_invoice_error", sa.Text(), nullable=True),
        sa.Column("flowaccount_supplier_invoice_id", sa.String(), nullable=True),
        sa.Column(
            "flowaccount_supplier_invoice_synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("flowaccount_payment_status", sa.String(), nullable=False),
        sa.Column("flowaccount_payment_error", sa.Text(), nullable=True),
        sa.Column(
            "flowaccount_payment_synced_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("flowaccount_linked_manually", sa.Boolean(), nullable=False),
        sa.Column("flowaccount_duplicate_override_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fund_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reference_no", sa.String(), nullable=False),
        sa.Column("source_bucket_id", sa.UUID(), nullable=False),
        sa.Column("target_bucket_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "source_balance_before", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "source_balance_after", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "target_balance_before", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "target_balance_after", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("source_balance_version", sa.String(), nullable=False),
        sa.Column("target_balance_version", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'THB'", name="ck_fund_allocation_currency"),
        sa.CheckConstraint(
            "status IN ('POSTED', 'REVERSED')", name="ck_fund_allocation_status"
        ),
        sa.CheckConstraint("amount > 0", name="ck_fund_allocation_positive_amount"),
        sa.CheckConstraint(
            "source_bucket_id <> target_bucket_id",
            name="ck_fund_allocation_distinct_buckets",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["fund_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_bucket_id"],
            ["fund_buckets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_bucket_id"],
            ["fund_buckets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("reference_no"),
        sa.UniqueConstraint("reversal_of", name="uq_fund_allocation_reversal_of"),
    )
    op.create_index(
        op.f("ix_fund_allocations_source_bucket_id"),
        "fund_allocations",
        ["source_bucket_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fund_allocations_target_bucket_id"),
        "fund_allocations",
        ["target_bucket_id"],
        unique=False,
    )
    op.create_table(
        "input_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("input_request_id", sa.UUID(), nullable=False),
        sa.Column("internal_reference", sa.String(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("bank_transfer_reference", sa.String(), nullable=True),
        sa.Column("paid_storage_prefix", sa.String(), nullable=False),
        sa.Column("recorded_by", sa.String(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["input_request_id"], ["input_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "input_request_id", name="uq_input_payments_input_request_id"
        ),
        sa.UniqueConstraint(
            "internal_reference", name="uq_input_payments_internal_reference"
        ),
    )
    op.create_index(
        op.f("ix_input_payments_input_request_id"),
        "input_payments",
        ["input_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_input_payments_internal_reference"),
        "input_payments",
        ["internal_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_input_payments_payment_date"),
        "input_payments",
        ["payment_date"],
        unique=False,
    )
    op.create_table(
        "input_request_line_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("input_request_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("work_type", sa.String(), nullable=True),
        sa.Column("request_type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["input_request_id"], ["input_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_input_request_line_items_input_request_id"),
        "input_request_line_items",
        ["input_request_id"],
        unique=False,
    )
    op.create_table(
        "installments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("boq_item_id", sa.UUID(), nullable=False),
        sa.Column("subcontractor_id", sa.String(), nullable=True),
        sa.Column("expense_category", sa.String(), nullable=True),
        sa.Column("expense_type", sa.String(), nullable=True),
        sa.Column("cost_type", sa.String(), nullable=True),
        sa.Column("installment_no", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("status", sa.String(), server_default="LOCKED", nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_overdue", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["boq_item_id"],
            ["boq_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fund_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("allocation_id", sa.UUID(), nullable=True),
        sa.Column("bucket_id", sa.UUID(), nullable=True),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["fund_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["fund_buckets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fund_audit_events_allocation_id"),
        "fund_audit_events",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fund_audit_events_bucket_id"),
        "fund_audit_events",
        ["bucket_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fund_audit_events_event_type"),
        "fund_audit_events",
        ["event_type"],
        unique=False,
    )
    op.create_table(
        "fund_ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("allocation_id", sa.UUID(), nullable=True),
        sa.Column("bucket_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('DEBIT', 'CREDIT')", name="ck_fund_ledger_direction"
        ),
        sa.CheckConstraint(
            "entry_type IN ('ALLOCATION', 'REVERSAL', 'OPENING_BALANCE', 'ADJUSTMENT')",
            name="ck_fund_ledger_entry_type",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_fund_ledger_nonnegative_amount"),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["fund_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["fund_buckets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_fund_ledger_entries_allocation_id"),
        "fund_ledger_entries",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fund_ledger_entries_bucket_id"),
        "fund_ledger_entries",
        ["bucket_id"],
        unique=False,
    )
    op.create_table(
        "input_payment_confirmations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("subcontractor_id", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("received_full_amount", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(), nullable=True),
        sa.Column("verification_note", sa.Text(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["input_payments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "payment_id",
            "idempotency_key",
            name="uq_input_payment_confirmations_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_input_payment_confirmations_payment_id"),
        "input_payment_confirmations",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_input_payment_confirmations_subcontractor_id"),
        "input_payment_confirmations",
        ["subcontractor_id"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("installment_id", sa.UUID(), nullable=False),
        sa.Column("subcontractor_id", sa.String(), nullable=True),
        sa.Column("base_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("vat_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("wht_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("retention_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "advance_deduction", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("net_payable", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["installment_id"],
            ["installments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Destructive baseline downgrade is intentionally unsupported")
