"""add BOQ V2 foundation

Revision ID: 20260915_0001
Revises: 20260915_0000
Create Date: 2026-09-15 11:46:13.492609
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260915_0001"
down_revision: Union[str, Sequence[str], None] = "20260915_0000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boq_v2_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_key", sa.String(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("command_type", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("calculation_version", sa.String(length=32), nullable=True),
        sa.Column("before_reference", sa.JSON(), nullable=True),
        sa.Column("after_reference", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key", name="uq_boq_v2_audit_event_key"),
    )
    op.create_index(
        "ix_boq_v2_audit_project_created",
        "boq_v2_audit_events",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "boq_v2_command_idempotency",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("command_type", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=True),
        sa.Column("response_reference", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'STARTED'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('STARTED', 'COMPLETED', 'FAILED')",
            name="ck_boq_v2_idempotency_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor",
            "project_id",
            "command_type",
            "idempotency_key",
            name="uq_boq_v2_command_idempotency",
        ),
    )
    op.create_index(
        "ix_boq_v2_idempotency_project_created",
        "boq_v2_command_idempotency",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "boq_v2_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("document_kind", sa.String(length=24), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=True),
        sa.Column("alternative_group_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(document_kind = 'ALTERNATIVE' AND alternative_group_id IS NOT NULL) OR (document_kind <> 'ALTERNATIVE' AND alternative_group_id IS NULL)",
            name="ck_boq_v2_document_alternative_group",
        ),
        sa.CheckConstraint(
            "(document_kind = 'CHANGE_ORDER' AND direction IN ('ADD', 'DEDUCT')) OR (document_kind <> 'CHANGE_ORDER' AND direction IS NULL)",
            name="ck_boq_v2_document_direction",
        ),
        sa.CheckConstraint(
            "document_kind IN ('MAIN', 'ALTERNATIVE', 'CHANGE_ORDER')",
            name="ck_boq_v2_document_kind",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_boq_v2_documents_project",
        "boq_v2_documents",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "boq_v2_project_budget_sources",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_kind",
            sa.String(length=8),
            server_default=sa.text("'LEGACY'"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('LEGACY', 'V2')", name="ck_boq_v2_budget_source_kind"
        ),
        sa.CheckConstraint("version > 0", name="ck_boq_v2_budget_source_version"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "boq_v2_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("predecessor_revision_id", sa.UUID(), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'DRAFT'"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "calculation_version",
            sa.String(length=32),
            server_default=sa.text("'boq-v2-calc-v1'"),
            nullable=False,
        ),
        sa.Column("net_sell_ex_vat", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "known_estimated_cost", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("forecast_cost", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("forecast_margin", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "required_cost_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "priced_cost_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ISSUED', 'ACCEPTED', 'WITHDRAWN', 'REJECTED', 'SUPERSEDED')",
            name="ck_boq_v2_revision_status",
        ),
        sa.CheckConstraint(
            "required_cost_count >= 0 AND priced_cost_count >= 0 AND priced_cost_count <= required_cost_count",
            name="ck_boq_v2_revision_cost_counts",
        ),
        sa.CheckConstraint("revision_number > 0", name="ck_boq_v2_revision_number"),
        sa.CheckConstraint("version > 0", name="ck_boq_v2_revision_version"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["boq_v2_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_revision_id"],
            ["boq_v2_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "revision_number", name="uq_boq_v2_revision_number"
        ),
    )
    op.create_index(
        "ix_boq_v2_revisions_project_status",
        "boq_v2_revisions",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "boq_v2_cost_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("scope_revision_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'WORKING'"),
            nullable=False,
        ),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "completeness_state",
            sa.String(length=16),
            server_default=sa.text("'INCOMPLETE'"),
            nullable=False,
        ),
        sa.Column(
            "required_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "priced_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "original_estimated_cost", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("agreed_cost", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("forecast_cost", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "calculation_version",
            sa.String(length=32),
            server_default=sa.text("'boq-v2-calc-v1'"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completeness_state = 'INCOMPLETE' OR (required_count = priced_count AND forecast_cost IS NOT NULL)",
            name="ck_boq_v2_complete_cost_plan_values",
        ),
        sa.CheckConstraint(
            "completeness_state IN ('COMPLETE', 'INCOMPLETE')",
            name="ck_boq_v2_cost_plan_completeness",
        ),
        sa.CheckConstraint(
            "status IN ('WORKING', 'PUBLISHED', 'SUPERSEDED')",
            name="ck_boq_v2_cost_plan_status",
        ),
        sa.CheckConstraint(
            "required_count >= 0 AND priced_count >= 0 AND priced_count <= required_count",
            name="ck_boq_v2_cost_plan_counts",
        ),
        sa.CheckConstraint("version > 0", name="ck_boq_v2_cost_plan_version"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_revision_id"],
            ["boq_v2_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "version", name="uq_boq_v2_cost_plan_version"
        ),
    )
    op.create_index(
        "uq_boq_v2_current_cost_plan",
        "boq_v2_cost_plans",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "boq_v2_scope_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("logical_id", sa.UUID(), nullable=False),
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("node_kind", sa.String(length=16), nullable=False),
        sa.Column(
            "inclusion_state",
            sa.String(length=16),
            server_default=sa.text("'REQUIRED'"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_code", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("specification", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column(
            "sell_material_unit_rate", sa.Numeric(precision=20, scale=4), nullable=True
        ),
        sa.Column(
            "sell_labor_unit_rate", sa.Numeric(precision=20, scale=4), nullable=True
        ),
        sa.Column(
            "sell_total",
            sa.Numeric(precision=20, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "inclusion_state IN ('REQUIRED', 'OPTIONAL', 'EXCLUDED')",
            name="ck_boq_v2_scope_inclusion_state",
        ),
        sa.CheckConstraint(
            "node_kind = 'ITEM' OR (quantity IS NULL AND unit IS NULL AND sell_material_unit_rate IS NULL AND sell_labor_unit_rate IS NULL AND sell_total = 0)",
            name="ck_boq_v2_structural_node_no_financials",
        ),
        sa.CheckConstraint(
            "node_kind IN ('SECTION', 'CATEGORY', 'SUBCATEGORY', 'ITEM')",
            name="ck_boq_v2_scope_node_kind",
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name="ck_boq_v2_scope_not_self_parent",
        ),
        sa.CheckConstraint("position >= 0", name="ck_boq_v2_scope_position"),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity >= 0", name="ck_boq_v2_scope_quantity"
        ),
        sa.CheckConstraint(
            "sell_labor_unit_rate IS NULL OR sell_labor_unit_rate >= 0",
            name="ck_boq_v2_scope_sell_labor_rate",
        ),
        sa.CheckConstraint(
            "sell_material_unit_rate IS NULL OR sell_material_unit_rate >= 0",
            name="ck_boq_v2_scope_sell_material_rate",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["boq_v2_scope_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["boq_v2_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "revision_id", "logical_id", name="uq_boq_v2_scope_revision_logical"
        ),
        sa.UniqueConstraint(
            "revision_id",
            "parent_id",
            "position",
            name="uq_boq_v2_scope_sibling_position",
        ),
    )
    op.create_index(
        "ix_boq_v2_scope_parent",
        "boq_v2_scope_nodes",
        ["revision_id", "parent_id"],
        unique=False,
    )
    op.create_index(
        "ix_boq_v2_scope_project_revision",
        "boq_v2_scope_nodes",
        ["project_id", "revision_id"],
        unique=False,
    )
    op.create_index(
        "uq_boq_v2_scope_root_position",
        "boq_v2_scope_nodes",
        ["revision_id", "position"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "boq_v2_cost_components",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cost_plan_id", sa.UUID(), nullable=False),
        sa.Column("scope_node_id", sa.UUID(), nullable=False),
        sa.Column("component_type", sa.String(length=16), nullable=False),
        sa.Column(
            "quantity_basis",
            sa.String(length=16),
            server_default=sa.text("'INHERITED'"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("specification", sa.Text(), nullable=True),
        sa.Column(
            "basis_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "cost_state",
            sa.String(length=20),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column("unit_rate", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("explicit_zero_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cost_state = 'UNKNOWN' AND unit_rate IS NULL AND total IS NULL) OR (cost_state = 'NOT_APPLICABLE' AND unit_rate IS NULL AND total = 0) OR (cost_state = 'PRICED' AND unit_rate IS NOT NULL AND unit_rate >= 0 AND total IS NOT NULL)",
            name="ck_boq_v2_cost_state_values",
        ),
        sa.CheckConstraint(
            "component_type IN ('MATERIAL', 'LABOR')",
            name="ck_boq_v2_cost_component_type",
        ),
        sa.CheckConstraint(
            "cost_state <> 'PRICED' OR unit_rate <> 0 OR length(trim(coalesce(explicit_zero_reason, ''))) > 0",
            name="ck_boq_v2_cost_explicit_zero_reason",
        ),
        sa.CheckConstraint(
            "cost_state IN ('UNKNOWN', 'PRICED', 'NOT_APPLICABLE')",
            name="ck_boq_v2_cost_state",
        ),
        sa.CheckConstraint(
            "quantity_basis IN ('INHERITED', 'OVERRIDDEN')",
            name="ck_boq_v2_cost_quantity_basis",
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_boq_v2_cost_quantity"),
        sa.ForeignKeyConstraint(
            ["cost_plan_id"],
            ["boq_v2_cost_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_node_id"],
            ["boq_v2_scope_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cost_plan_id",
            "scope_node_id",
            "component_type",
            name="uq_boq_v2_cost_plan_node_component",
        ),
    )
    op.create_index(
        "ix_boq_v2_cost_components_node",
        "boq_v2_cost_components",
        ["scope_node_id"],
        unique=False,
    )
    op.create_table(
        "boq_v2_project_baselines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("main_revision_id", sa.UUID(), nullable=False),
        sa.Column("cost_plan_id", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "calculation_version",
            sa.String(length=32),
            server_default=sa.text("'boq-v2-calc-v1'"),
            nullable=False,
        ),
        sa.Column("net_sell_ex_vat", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "original_estimated_cost", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("agreed_cost", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("forecast_cost", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("forecast_margin", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_active OR (activated_at IS NOT NULL AND effective_to IS NULL)",
            name="ck_boq_v2_active_baseline_identity",
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name="ck_boq_v2_baseline_effective_range",
        ),
        sa.CheckConstraint("version > 0", name="ck_boq_v2_baseline_version"),
        sa.ForeignKeyConstraint(
            ["cost_plan_id"],
            ["boq_v2_cost_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["main_revision_id"],
            ["boq_v2_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_boq_v2_baseline_version"),
    )
    op.create_index(
        "uq_boq_v2_active_project_baseline",
        "boq_v2_project_baselines",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "boq_v2_baseline_change_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("baseline_id", sa.UUID(), nullable=False),
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_boq_v2_baseline_co_position"),
        sa.ForeignKeyConstraint(
            ["baseline_id"],
            ["boq_v2_project_baselines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["boq_v2_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "baseline_id", "position", name="uq_boq_v2_baseline_co_position"
        ),
        sa.UniqueConstraint(
            "baseline_id", "revision_id", name="uq_boq_v2_baseline_co_revision"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Destructive BOQ V2 downgrade is intentionally unsupported")
